sources:
  - name: src_transactions
    description: "The source table for transactions"  # optional
    connection: default           # optional - if not provided, will use the connection named "default" or the default connection specified in settings
    table: expenses               # optional - if not provided, will use the "name" field of the source
    load_to_duckdb: true          # optional - default is false - outside of dbview models that have translate_to_duckdb as false, other models can only reference this source if load_to_duckdb is true

    # For performance reasons, avoid specifying primary_key for large tables if upserts are not required
    primary_key: [id]             # optional - if not provided, then this is an insert-only table for incremental loads - otherwise, this uses upsert
    
    update_hints:
      increasing_column: date     # optional - if not provided, will always do full refresh, otherwise uses this column for incremental loads
      strictly_increasing: false  # optional - default is true - if false, then maximum value of column is removed before incremental loads

    columns:                      # optional - if load_to_duckdb is true, then only the columns listed here are loaded to duckdb
      - name: id
        type: string
        description: The unique identifier for the transaction
        category: dimension

      - name: date
        type: date
        description: The date of the transaction
        category: dimension

      - name: subcategory_id
        type: string
        description: The ID of the subcategory of the transaction
        category: dimension

      - name: amount
        type: float
        description: The amount of the transaction
        category: measure

      - name: description
        type: string
        description: The description of the transaction
        category: dimension
