sources:
  - name: src_transactions
    connection: default              # optional - if not provided, will use the default connection specified in settings
    table: transactions              # optional - if not provided, will use the name of the source
    primary_key: [id]                # optional - defaults to empty list where no primary key is assumed
    
    update_hints:
      increasing_column: date        # optional - defaults to null - when not null, incremental loading occurs, otherwise will do a full refresh
      strictly_increasing: false     # optional - defaults to true - when false, the max value of the increasing column is deleted before incremental loads
      
    columns:
      - name: id
        type: string
        description: The unique identifier for the transaction

      - name: date
        type: date
        description: The date of the transaction
      
      - name: category
        type: string
        description: The category of the transaction

      - name: subcategory
        type: string
        description: The subcategory of the transaction

      - name: amount
        type: float
        description: The amount of the transaction

      - name: description
        type: string
        description: The description of the transaction
