site_name: Squirrels Documentation
site_url: https://ty2huang.github.io/squirrels/

theme: readthedocs

nav:
- Home: index.md
- Getting Started: getting-started.md
- Overview: overview.md
- CLI Commands:
  - init: cli-guide/init.md
  - set-profile: cli-guide/set-profile.md
  - get-all-profiles: cli-guide/get-all-profiles.md
  - delete-profile: cli-guide/delete-profile.md
  - load-modules: cli-guide/load-modules.md
  - test: cli-guide/test.md
  - run: cli-guide/run.md
- Project Files:
  - squirrels.yaml: user-guide/squirrels-manifest.md
  - parameters.py: user-guide/parameters.md
  - context.py: user-guide/context.md
  - database views: user-guide/database-views.md
  - final view: user-guide/final-view.md
  - selections.cfg: user-guide/selections.md
  - sample_lu_data.xlsx: user-guide/sample-lu-data.md

markdown_extensions:
- admonition
