# Squirrels CLI commands
INIT_CMD = 'new'
GET_FILE_CMD = 'get-file'
DEPS_CMD = 'deps'
BUILD_CMD = 'build'
COMPILE_CMD = 'compile'
RUN_CMD = 'run'
DUCKDB_CMD = 'duckdb'

# Environment variables
SQRL_SECRET_KEY = 'SQRL_SECRET__KEY'
SQRL_SECRET_ADMIN_PASSWORD = 'SQRL_SECRET__ADMIN_PASSWORD'

SQRL_AUTH_DB_FILE_PATH = 'SQRL_AUTH__DB_FILE_PATH'
SQRL_AUTH_TOKEN_EXPIRE_MINUTES = 'SQRL_AUTH__TOKEN_EXPIRE_MINUTES'
SQRL_AUTH_CREDENTIAL_ORIGINS = 'SQRL_AUTH__ALLOWED_ORIGINS_FOR_COOKIES'

SQRL_PARAMETERS_CACHE_SIZE = 'SQRL_PARAMETERS__CACHE_SIZE'
SQRL_PARAMETERS_CACHE_TTL_MINUTES = 'SQRL_PARAMETERS__CACHE_TTL_MINUTES'
SQRL_PARAMETERS_DATASOURCE_REFRESH_MINUTES = 'SQRL_PARAMETERS__DATASOURCE_REFRESH_MINUTES'

SQRL_DATASETS_CACHE_SIZE = 'SQRL_DATASETS__CACHE_SIZE'
SQRL_DATASETS_CACHE_TTL_MINUTES = 'SQRL_DATASETS__CACHE_TTL_MINUTES'
SQRL_DATASETS_MAX_ROWS_FOR_AI = 'SQRL_DATASETS__MAX_ROWS_FOR_AI'

SQRL_DASHBOARDS_CACHE_SIZE = 'SQRL_DASHBOARDS__CACHE_SIZE'
SQRL_DASHBOARDS_CACHE_TTL_MINUTES = 'SQRL_DASHBOARDS__CACHE_TTL_MINUTES'

SQRL_SEEDS_INFER_SCHEMA = 'SQRL_SEEDS__INFER_SCHEMA'
SQRL_SEEDS_NA_VALUES = 'SQRL_SEEDS__NA_VALUES'

SQRL_CONNECTIONS_DEFAULT_NAME_USED = 'SQRL_CONNECTIONS__DEFAULT_NAME_USED'

SQRL_VDL_CATALOG_DB_PATH = 'SQRL_VDL__CATALOG_DB_PATH'
SQRL_VDL_DATA_PATH = 'SQRL_VDL__DATA_PATH'

SQRL_STUDIO_BASE_URL = 'SQRL_STUDIO__BASE_URL'

SQRL_LOGGING_LOG_LEVEL = 'SQRL_LOGGING__LOG_LEVEL'
SQRL_LOGGING_LOG_FORMAT = 'SQRL_LOGGING__LOG_FORMAT'
SQRL_LOGGING_LOG_TO_FILE = 'SQRL_LOGGING__LOG_TO_FILE'
SQRL_LOGGING_LOG_FILE_SIZE_MB = 'SQRL_LOGGING__LOG_FILE_SIZE_MB'
SQRL_LOGGING_LOG_FILE_BACKUP_COUNT = 'SQRL_LOGGING__LOG_FILE_BACKUP_COUNT'

# Folder/File names
PACKAGE_DATA_FOLDER = '_package_data'
BASE_PROJECT_FOLDER = 'base_project'

GLOBAL_ENV_FOLDER = '.squirrels'
MANIFEST_JINJA_FILE = 'squirrels.yml.j2'
CONNECTIONS_YML_FILE = 'connections.yml'
PARAMETERS_YML_FILE = 'parameters.yml'
DASHBOARDS_YML_FILE = 'dashboards.yml'
MANIFEST_FILE = 'squirrels.yml'
DUCKDB_INIT_FILE = 'duckdb_init.sql'
DOTENV_FILE = '.env'
DOTENV_LOCAL_FILE = '.env.local'
GITIGNORE_FILE = '.gitignore'

LOGS_FOLDER = 'logs'
LOGS_FILE = 'squirrels.log'

DATABASE_FOLDER = 'assets'
PACKAGES_FOLDER = 'sqrl_packages'
PUBLIC_FOLDER = 'public'

MACROS_FOLDER = 'macros'
MACROS_FILE = 'macros_example.sql'

MODELS_FOLDER = 'models'
SOURCES_FILE = 'sources.yml'
BUILDS_FOLDER = 'builds'
BUILD_FILE_STEM = 'build_example'
DBVIEWS_FOLDER = 'dbviews'
DBVIEW_FILE_STEM = 'dbview_example'
FEDERATES_FOLDER = 'federates'
FEDERATE_FILE_STEM = 'federate_example'

DASHBOARDS_FOLDER = 'dashboards'
DASHBOARD_FILE_STEM = 'dashboard_example'

PYCONFIGS_FOLDER = 'pyconfigs'
AUTH_FILE = 'auth.py'
CONNECTIONS_FILE = 'connections.py'
CONTEXT_FILE = 'context.py'
PARAMETERS_FILE = 'parameters.py'
USER_FILE = 'user.py'
ADMIN_USERNAME = 'admin'

TARGET_FOLDER = 'target'
COMPILE_FOLDER = 'compile'
COMPILE_BUILDTIME_FOLDER = 'buildtime'
COMPILE_RUNTIME_FOLDER = 'runtime'
DB_FILE = 'auth.sqlite'
DEFAULT_VDL_CATALOG_DB_PATH = 'ducklake:{project_path}/target/vdl_catalog.duckdb'
DEFAULT_VDL_DATA_PATH = '{project_path}/target/vdl_data/'

SEEDS_FOLDER = 'seeds'
SEED_CATEGORY_FILE_STEM = 'seed_categories'
SEED_SUBCATEGORY_FILE_STEM = 'seed_subcategories'

# Test sets
DEFAULT_TEST_SET_NAME = 'default'
USER_ATTRIBUTES_SECTION = 'user_attributes'
PARAMETERS_SECTION = 'parameters'

# Init Command Choices
SQL_FILE_TYPE = 'sql'
PYTHON_FILE_TYPE = 'py'
FILE_TYPE_CHOICES = [SQL_FILE_TYPE, PYTHON_FILE_TYPE]

YML_FORMAT = 'yml'
PYTHON_FORMAT = 'py'
CONF_FORMAT_CHOICES = [YML_FORMAT, PYTHON_FORMAT]

PYTHON_FORMAT2 = 'py (recommended)'
CONF_FORMAT_CHOICES2 = [(PYTHON_FORMAT2, PYTHON_FORMAT), YML_FORMAT]

EXPENSES_DB = 'expenses.db'
WEATHER_DB = 'weather.db'

# Dashboard formats
PNG = "png"
HTML = "html"

# Function names
MAIN_FUNC = "main"

# Regex
DATE_REGEX = r"^\d{4}\-\d{2}\-\d{2}$"
COLOR_REGEX = r"^#[0-9a-fA-F]{6}$"

# OAuth2
SUPPORTED_SCOPES = ['read']
SUPPORTED_GRANT_TYPES = ['authorization_code', 'refresh_token']
SUPPORTED_RESPONSE_TYPES = ['code']
