parameters:
  - type: SingleSelectParameter
    factory: CreateWithOptions                            ## one of 'CreateSimple', 'CreateWithOptions', or 'CreateFromSource'
    arguments:                                            ## arguments to specify depend on values for 'type' and 'factory'
      name: group_by
      label: Group By
      description: Dimension(s) to aggregate by           ## optional, default is empty string
      user_attribute: role                                ## optional, default is null
      all_options:
        - id: g0
          label: Transaction
          columns: ["date", "category", "subcategory", "description"]   ## custom field
          is_default: false                               ## optional, default, exists for SingleSelect or MultiSelect options only
          user_groups: ["manager"]                        ## optional, default is empty list
          parent_option_ids: []                           ## optional, default, exists for all parameter options
        - id: g1
          label: Day
          columns: [date]
          aliases: [day]                                  ## custom field
          user_groups: ["manager", "employee"]
        - id: g4
          label: Month
          columns: [month]
          user_groups: ["manager", "employee"]
        - id: g2
          label: Category
          columns: [category]
          user_groups: ["manager", "employee"]
        - id: g3
          label: Subcategory
          columns: [category, subcategory]
          user_groups: ["manager", "employee"]
      parent_name: null                                   ## optional, default, exists for all parameter types
  
  - type: NumberParameter
    factory: CreateWithOptions
    arguments:
      name: limit
      label: Max Number of Rows
      description: Maximum number of rows to return
      parent_name: group_by
      all_options:
        - min_value: 0
          max_value: 1000
          increment: 10
          default_value: 1000
          parent_option_ids: g0
  
  - type: DateParameter
    factory: CreateFromSource
    arguments:
      name: start_date
      label: Start Date
      description: Start date to filter transactions by
      data_source:
        table_or_query: SELECT min(date) AS min_date, max(date) AS max_date FROM expenses
        default_date_col: min_date
        min_date_col: min_date
        max_date_col: max_date
  
  - type: DateParameter
    factory: CreateWithOptions
    arguments:
      name: end_date
      label: End Date
      description: End date to filter transactions by
      all_options:
        - default_date: 2024-12-31
          min_date: 2024-01-01
          max_date: 2024-12-31
  
  - type: DateRangeParameter
    factory: CreateWithOptions
    arguments:
      name: date_range
      label: Date Range
      description: Date range to filter transactions by
      all_options:
        - default_start_date: 2024-01-01
          default_end_date: 2024-12-31
          min_date: 2024-01-01
          max_date: 2024-12-31
  
  - type: MultiSelectParameter
    factory: CreateFromSource
    arguments:
      name: category
      label: Category Filter
      description: The expense categories to filter transactions by
      data_source:
        table_or_query: seed_categories
        id_col: category_id
        options_col: category
        from_seeds: true                                  ## optional, default is false, exists for data_source of any parameters
        order_by_col: null                                ## optional, default, exists for data_source of SingleSelect and MultiSelect
        is_default_col: null                              ## optional, default, exists for data_source of SingleSelect and MultiSelect
        custom_cols: {}                                   ## optional, default, exists for data_source of SingleSelect and MultiSelect
        include_all: true                                 ## optional, default, exists for data_source of MultiSelect only
        order_matters: false                              ## optional, default, exists for data_source of MultiSelect only
        user_group_col: null                              ## optional, default, exists for data_source of any parameters
        connection_name: default                          ## optional, default, exists for data_source of any parameters
  
  - type: MultiSelectParameter
    factory: CreateFromSource
    arguments:
      name: subcategory
      label: Subcategory Filter
      description: The expense subcategories to filter transactions by (available options are based on selected value(s) of 'Category Filter')
      parent_name: category
      data_source:
        table_or_query: seed_subcategories
        id_col: subcategory_id
        options_col: subcategory
        from_seeds: true
        parent_id_col: category_id                        ## optional, default is null, exists for all parameter types
  
  - type: NumberParameter
    factory: CreateWithOptions
    arguments:
      name: min_filter
      label: Amounts Greater Than
      description: Number to filter on transactions with an amount greater than this value
      all_options:
        - min_value: 0
          max_value: 300
          increment: 10                                   ## optional, default is 1, exists for Number and NumberRange options
          default_value: null                             ## optional, default, exists for Number options only
  
  - type: NumberParameter
    factory: CreateFromSource
    arguments:
      name: max_filter
      label: Amounts Less Than
      description: Number to filter on transactions with an amount less than this value
      data_source:
        table_or_query: "SELECT 0 as min_value, 300 as max_value, 10 as increment"
        min_value_col: min_value
        max_value_col: max_value
        increment_col: increment                          ## optional, default is null
        default_value_col: max_value                      ## optional, default is null
        id_col: null                                      ## optional, default, required for SingleSelect and MultiSelect, optional for others
  
  - type: NumberRangeParameter
    factory: CreateWithOptions
    arguments:
      name: between_filter
      label: Amounts Between
      description: Number range to filter on transactions with an amount within this range
      all_options:
        - min_value: 0
          max_value: 300
          default_lower_value: 0                          ## optional, default is null (or min_value), exists for NumRange options only
          default_upper_value: 300                        ## optional, default is null (or max_value), exists for NumRange options only


